name: Release
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@gatanaso"
      - name: Clean 'yarn' cache
        run: yarn cache clean
      - name: Install dependencies
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
