name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Major, minor or patch?"
        required: true
        options:
          - prerelease
          - premajor
          - preminor
          - prepatch
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@gatanaso"
      - name: Git config
        run: |
          git config user.name ${{github.actor}}
          git config user.email ${{github.actor}}@users.noreply.github.com
      - name: Clean 'yarn' cache
        run: yarn cache clean
      - name: Install dependencies
        run: yarn install
      - name: Release to GitHub
        run: yarn run release:${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package to GitHub Packages
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
